#!/bin/bash

file=$1

if [ -z $1 ]; then
   echo "Where is the file to convert?"
   exit 1
fi

if [[ -d $1 ]]; then
 for f in $file/*;
 do
  filename="${f%.*}"
  ffmpeg -i "$f" -acodec mp3 -ac 2 -ab 192k "$filename.mp3"
  echo "Deleting file: $f"
  rm "$f"
 done
else
 filename="${file%.*}"
 ffmpeg -i "$file" -acodec mp3 -ac 2 -ab 192k "$filename".mp3
 rm "$file"
 echo "Done"
fi 
